- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
- config/unicorn.rb
> capistranoの設定

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/common.scss
- app/assets/stylesheets/mixin/main-header.scss
- app/assets/stylesheets/modules/cards.scss
- app/assets/stylesheets/modules/main-header.scss
- app/assets/stylesheets/modules/top-header.scss
- app/controllers/products_controller.rb
- app/views/products/_header.html.haml
- app/views/products/_main-header.html.haml
- app/views/products/index.html.haml
- config/routes.rb
メインヘッダーの作成
他の画面に遷移するためのリンクを設定（ルーティングはマージ後に設定）
> markup-main-header

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/mypage.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/cards.scss
- app/assets/stylesheets/modules/mypages.scss
- app/assets/stylesheets/modules/side-menu.scss
- app/views/mypages/index.html.haml
マイページのトップ画面を実装する。
ユーザーの情報などを参照・編集できるページが必要だから。
> Add mypage view

- config/environments/production.rb
jQueryを使うために、一箇所コメントアウトをする。
本番環境でエラーを出してしまうため。
> CommentOut

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/mixin/button.scss
- app/assets/stylesheets/mixin/main-header.scss
- app/assets/stylesheets/modules/main-header.scss
- app/views/products/_main-header.html.haml
メインヘッダーのナビゲーション作成
他画面に遷移するための画面を作成
> メインヘッダーのメークアップ

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/base/product/buy.scss
- app/assets/stylesheets/config/color.scss
- app/assets/stylesheets/mixin/text.scss
- app/controllers/products_controller.rb
- app/views/products/buy.html.haml
- config/routes.rb
#WHAT
購入確認ページのマークアップ
#WHY
商品の購入機能を使用できる画面を作成するため
> 購入確認ページのマークアップ

- Gemfile
- Gemfile.lock
- app/assets/javascripts/card.js
- app/assets/stylesheets/modules/signup.scss
- app/controllers/cards_controller.rb
- app/controllers/products_controller.rb
- app/views/cards/index.html.haml
- app/views/cards/new.html.haml
- app/views/layouts/application.html.haml
- app/views/products/buy.html.haml
- config/routes.rb
- db/migrate/20190604045115_add_card_info_to_users.rb
- db/schema.rb
Payjpを利用して、商品を購入できるようにする。
（単体テストは別途プルリクエストを出す予定。）
ユーザーが商品を購入できるようにする必要があるから。
> Add buy product function

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/modules/logout.scss
- app/assets/stylesheets/modules/myprofile-edit.scss
- app/controllers/users_controller.rb
- app/views/users/logout.html.haml
- config/routes.rb
* ログアウトのマークアップ
[![Image from Gyazo](https://i.gyazo.com/09ff689d1f8a14330b15c1d4566cc164.png)](https://gyazo.com/09ff689d1f8a14330b15c1d4566cc164)
> ログアウトのマークアップ

- app/assets/stylesheets/modules/cards.scss
- app/assets/stylesheets/modules/mypages.scss
- app/assets/stylesheets/modules/side-menu.scss
- app/views/cards/index.html.haml
- app/views/cards/new.html.haml
- app/views/mypages/index.html.haml
マイページにフッターをつけると、ビューが崩れる問題対応。
見た目が悪いから。
> Modify mypage view

- spec/controllers/cards_controller_spec.rb
- spec/controllers/products_controller_spec.rb
- spec/factories/products.rb
- spec/factories/users.rb
商品購入の単体テストを行う。
テストを実施することで、品質の確保を図る。
> Add buy product test

- app/assets/stylesheets/base/product/show.scss
- app/controllers/cards_controller.rb
- app/controllers/products_controller.rb
- app/models/delivery_fee_burden.rb
- app/models/delivery_method.rb
- app/models/product.rb
- app/views/cards/index.html.haml
- app/views/products/_product-list.html.haml
- app/views/products/_show-products.html.haml
- app/views/products/buy.html.haml
- app/views/products/show.html.haml
- config/routes.rb
- db/seeds.rb
商品詳細ページでDBの商品情報を表示できるようにサーバサイドを実装する。
ユーザーが商品の詳細を見れるようにするため。
> AddProductShowFunction

- spec/controllers/cards_controller_spec.rb
- spec/controllers/products_controller_spec.rb
- spec/factories/users.rb
商品詳細ページのサーバサード実装の単体テストを行う。
単体テストを実施することで、品質の確保を図る。
> Add product show test

- app/assets/javascripts/delete.js
- app/assets/stylesheets/base/product/show.scss
- app/assets/stylesheets/modules/mypages.scss
- app/assets/stylesheets/modules/side-menu.scss
- app/controllers/mypages_controller.rb
- app/controllers/products_controller.rb
- app/models/product.rb
- app/views/layouts/_sidemenu.html.haml
- app/views/mypages/seller_product.html.haml
- app/views/mypages/selling_list.html.haml
- config/routes.rb
- db/migrate/20190609065234_change_column_to_image.rb
- db/migrate/20190609065401_add_forignkey_to_image.rb
- db/schema.rb
商品の削除機能を実装する。
（単体テストの実装は別途行う予定。）
出品した商品を削除する必要があるから。
> Add product delete function

- spec/controllers/mypages_controller_spec.rb
商品削除機能の単体テストを行う。
テストを実施することで品質の確保を図る。
> Add product delete test

- app/assets/javascripts/card.js
- app/controllers/users_controller.rb
- app/views/users/address_registration.html.haml
- app/views/users/card_registration.html.haml
ユーザー新規登録画面でクレジットカードを登録できるようにする。
（現状の実装では、新規登録の画面ではクレジットカード登録画面を表示していない。）
商品を購入するために登録が必要だから。
> Add transition signup view

- app/controllers/products_controller.rb
- spec/controllers/products_controller_spec.rb
検索機能の追加
検索機能の単体テスト
商品名の検索を可能にする
[![Image from Gyazo](https://i.gyazo.com/dcdb7091a3249906bcc03f9ee7177cf7.png)](https://gyazo.com/dcdb7091a3249906bcc03f9ee7177cf7)
> Add search function

- app/assets/javascripts/main-header.js
- app/assets/javascripts/product-detail-search.js
- app/assets/stylesheets/base/product/search.scss
- app/controllers/categories_controller.rb
- app/controllers/products_controller.rb
- app/helpers/application_helper.rb
- app/helpers/products_helper.rb
- app/models/product.rb
- app/views/products/detail_search.json.jbuilder
- app/views/products/search.html.haml
- app/views/shared/_main-header.html.haml
- config/routes.rb
詳細検索（商品名, ソート順）機能
詳細検索のビュー修正
条件検索を可能とする
[![Image from Gyazo](https://i.gyazo.com/a51259b50a70f475ceda4bd99e8bb040.gif)](https://gyazo.com/a51259b50a70f475ceda4bd99e8bb040)
[![Image from Gyazo](https://i.gyazo.com/8d0320299f8978d4610bdec9ded243e8.gif)](https://gyazo.com/8d0320299f8978d4610bdec9ded243e8)
> Add detail search function(name & sort)

- app/controllers/products_controller.rb
- app/controllers/sessions_controller.rb
- app/views/layouts/_sidemenu.html.haml
- app/views/mypages/likes_list.html.haml
- app/views/mypages/logout.html.haml
- app/views/mypages/myconfirmation.html.haml
- app/views/mypages/seller_product.html.haml
- app/views/mypages/selling_list.html.haml
- app/views/mypages/show.html.haml
- app/views/products/show.html.haml
- config/breadcrumbs.rb
- config/puma.rb
パンくずリストを追加する。
その他にも、バグ対応を盛り込む。
品質を上げるため。
> Add pan list

- app/assets/javascripts/product-detail-search.js
- app/assets/stylesheets/modules/_breadcrumbs.scss
- app/views/categories/show.html.haml
- app/views/products/search.html.haml
- config/breadcrumbs.rb
> パンくずリストの作成

- app/assets/javascripts/drag-and-drop.js
- app/assets/javascripts/sell.js
- app/controllers/products_controller.rb
- app/views/mypages/seller_product.html.haml
- app/views/products/edit.html.haml
- app/views/products/image.json.jbuilder
- config/routes.rb
商品の編集機能を実装する。
出品した商品の情報を変更する場合があるから。
> Add product edit function
